#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# | Copyright m3rlinux 2020                    m3rlinux.it@gmail.com |
# +------------------------------------------------------------------+
#
# This file extend check snmp for Check_MK
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Davide Gibilisco <m3rlinux.it@gmail.com>
# Damocles
# '.1.3.6.1.4.1.21796.3.4.1.1.3' => Check Name
# '.1.3.6.1.4.1.21796.3.4.1.1.2' => Check Value

def inventory_damocles(info):
    for line in info:
        yield line[0], None


def check_damocles(item, _no_params, info):
    for check, state in info:
        if check == item:
            if state == "0":
                return 0, "OK"
            else:
                return 2, "CRIT"


check_info["damocles"] = {
    'check_function': check_damocles,
    'inventory_function': inventory_damocles,
    'service_description': '',
    'snmp_info': ('.1.3.6.1.4.1.21796.3.4.1.1', ['3', '2']),
    'snmp_scan_function': \
        lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.21796.") or \
                    oid(".1.3.6.1.4.1.1.2.0") == "damocles",
}