#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Check_MK Cloudmark Info Plugin
#
# Copyright 2019, Davide Gibilisco <m3rlinux.it@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# check_mk --debug -nv --checks=cloudmark some.host-cloudmark.dom

# example output
# <<<cloudmark>>>
# Queue 72
# Delivery 8830
# Concurrency 5573

# Threshold
factory_settings["cloudmark_default_levels"] = {
    "Queue"     : ( 5000, 10000 ),
    "Delivery"     : ( 5000, 30000 ),
    "Concurrency" : ( 8000, 10000 ),
}


def inventory_cloudmark(info):
    for line in info:
        key = line[0]
        value = line[1]
        if key == "Queue":
            yield key, {}
        elif key == "Delivery":
            yield key, {}
        elif key == "Concurrency":
            yield key, {}

def check_cloudmark(item, params, info):
    for line in info:
        key = line[0]
        if key == item:
            if item == 'Queue':
                warn = params['Queue'][0]
                crit = params['Queue'][1]
            elif item == 'Delivery':
                warn = params['Delivery'][0]
                crit = params['Delivery'][1]
            elif item == 'Concurrency':
                warn = params['Concurrency'][0]
                crit = params['Concurrency'][1]
            val = int(line[1])
            perfdata = [ ( item, val, warn, crit ) ]
            if val > crit:
                return 2, "Mail %s is %d" % (item, val), perfdata
            elif val > warn:
                return 1, "Mail %s is %d" % (item, val), perfdata
            else:
                return 0, "Mail %s is %d" % (item, val), perfdata

check_info["cloudmark"] = {
    'check_function':            check_cloudmark,
    'inventory_function':        inventory_cloudmark,
    "default_levels_variable" : "cloudmark_default_levels",
    'service_description':       'Cloudmark %s',
    'has_perfdata':              True,
    'group': "cloudmark",
}
